# name: Build on all platforms

# on: [push]

# jobs:
#   build_win64:
#     runs-on: windows-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
#       - name: python -m build
#         run: |
#           python -m pip install --user requests
#           python -m build norun
#       - name: Archive production artifacts
#         uses: actions/upload-artifact@v2
#         with:
#           name: dist-win64
#           path: |
#             main.exe

#   build_linux64:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
#       - name: python -m build
#         run: |
#           python -m pip install --user requests
#           python -m build norun
#       - name: Archive production artifacts
#         uses: actions/upload-artifact@v2
#         with:
#           name: dist-linux64
#           path: |
#             main

